name: GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check vulnerabilities in dependencies
        run: npm audit
